"""remove position

Revision ID: 38cdbb1464a9
Revises: 54a78bc54ccd
Create Date: 2026-10-08 16:44:28.486538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cdbb1464a9'
down_revision: Union[str, Sequence[str], None] = '54a78bc54ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
