"""remove email

Revision ID: d2e4d7a5cec7
Revises: 38cdbb1464a9
Create Date: 2026-10-08 17:11:07.187793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e4d7a5cec7'
down_revision: Union[str, Sequence[str], None] = '38cdbb1464a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'recipient_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('recipient_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
